# Generated by Django 3.1.6 on 2021-02-10 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloth',
            name='image',
            field=models.ImageField(default=None, upload_to='clothes/%Y/%m/%d/'),
        ),
    ]
