# Generated by Django 3.1.6 on 2021-02-11 12:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clothes', '0002_cloth_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('like', 'like'), ('dislike', 'dislike')], default=None, max_length=7, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='cloth',
            options={'verbose_name_plural': 'Clothes'},
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.AddField(
            model_name='opinion',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clothes.cloth'),
        ),
        migrations.AddField(
            model_name='opinion',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
