# Generated by Django 3.1.6 on 2021-02-11 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothes', '0003_auto_20210211_1204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='cloth',
            new_name='product',
        ),
    ]
